[package]
name = "jtag_boot"
version = "0.1.0"
authors = ["Andre Richter <andre.o.richter@gmail.com>"]
edition = "2018"

[dependencies]
raspi3_boot = { path = "raspi3_boot" }
cortex-a = "2.3.1"
register = "0.3.3"

[package.metadata.cargo-xbuild]
sysroot_path = "../xbuild_sysroot"
